### PR TITLE
Reformat whitespace, fix a merge oopsies, fix voting on series level, fix other minor errors

### PR DESCRIPTION
**Pull request by da3dsoul**
Finally fixed whatever my git did to that poor branch

### CODE REVIEW

**Comment by bigretromike** [comment]
let me review this :-)

**Comment by bigretromike** [comment]
so its empty. merge to be on same branch

**Comment by da3dsoul** [comment]
Github has a really bad diff implementation when it comes to whitespace. You should be able to click a button, and it hides all whitespace changes

**Comment by bigretromike** [comment]
why did you revert the import order ?

**Comment by bigretromike** [comment]
also there are few broken lines i dont like which make them hard to read ex. line 206

**Comment by da3dsoul** [comment]
I just ran the code formatter on it after setting up the whitespace properly.

**Comment by bigretromike** [comment]
It look cleaner, but few 'cleaner' lines are harder to read because of being split on 2 lines instead of 1

**Comment by bigretromike** [comment]
I pushed https://github.com/japanesemediamanager/jmmserver/commit/d2bd1fbf43da526fd1e4e892800e767e76269346 this so it should fix blank/missing/corrupt cache problem inside kodi

**Comment by da3dsoul** [comment]
I see what you mean. I'll fix that in my formatter

**Pull request merged**
