### PR TITLE
Add More Info context menu option and some other little things non-functional

### PR DESCRIPTION
**Pull request by da3dsoul**

### CODE REVIEW

**Comment by bigretromike** [comment]
I see you started +2h before me today with actor/cast thing :+1:

**Comment by da3dsoul** [comment]
We really need to rewrite the jmm side for cast and tags. Tags are sent with every episode, they need only be sent once. Cast is sent in the first episode, which is not always the first read in the iteration. I'm waiting on 3 prs for jmmserver and 1 for jmmclient before I start optimizing and rewriting that (I've mainly worked on games, not multimedia, so my knowledgebase frowns on plain text networking). Also going to add a bunch of new filters that were requested, but that is irrelevant.

**Comment by bigretromike** [comment]
^_^
Yeah, JMM Side need to be rewriten

**Comment by da3dsoul** [comment]
Out of curiousity, what IDE do you use for python? I use IntelliJ IDEA for java, and just reconfigured my workspace for the project.

**Comment by bigretromike** [comment]
vim (less) notepad++ (more) depend where I am - everything im doing by hand, but that will soon change because I started other python project that would be great to have my "IDE" done by then

**Pull request merged**
