### PR TITLE
Add Log Spam w/ setting. Add setting to truncate data on long shows. Fix Tags #79

### PR DESCRIPTION
**Pull request by da3dsoul**

### CODE REVIEW

**Comment by da3dsoul** [comment]
#83 is relevant

**Comment by da3dsoul** [comment]
Yes

**Comment by bigretromike** [comment]
Tags are already fixed. But I will merge this anyway and if needed overwrite it with better version if mine will be :-) probably not but I like that you try to improve mine project :+1:

**Comment by bigretromike** [comment]
I wanted to push mine version today but I will have to rework it with those pushes from you :+1:

**Pull request merged**
