### PR TITLE
Add tag blacklist and setting. Edit the Error system to give more info

### PR DESCRIPTION
**Pull request by da3dsoul**

### CODE REVIEW

**Comment by da3dsoul** [comment]
Don't merge this yet, it doesn't work on android

**Comment by bigretromike** [comment]
code look and thanks for making 'error' better, I didn't know how to make that :+1:

**Comment by da3dsoul** [comment]
...I hit an error and googled it. Pretty much how I've done everything so far...

**Comment by da3dsoul** [comment]
Go for it. Let me know if you have any arguments on the tags I chose to hide. Some of them I was back and forth on, like animation styles, censoring, etc. I chose to hide them and stick with a purely plot related  tag system.

**Comment by bigretromike** [comment]
Im not sure but I would love to be able tick/untick them in settings but from what I search kodi (15.x) didn't support parsing data from file into making settings, probably there should be script to rewrite settings.xml but that a overkill. Few tags I would leave, but for now no one ever complain about them (not being seen ;-) ) so they have option for that. Thanks once again for your contribution in my project.

**Comment by da3dsoul** [comment]
Yeah, I tend to join projects at the drop of a hat. I see a few things that bug me, then I get impatient, then half of the issues list is fixed/implemented...

**Comment by da3dsoul** [comment]
I think outside editors is easier. Being able to change the list would be nice, but I can only imagine scrolling through a thousand tags and checking or unchecking each one.

**Comment by bigretromike** [comment]
Still I think that would be better for pad/tv users than editing file by hand each time new version come out xD

**Pull request merged**
